### PR TITLE
Expose operations, including "historical" operations

### LINKED ISSUE #373: Expose operations from TaskChampion
## Background

Every change to a task is represented internally as an "Operation"
https://github.com/GothenburgBitFactory/taskwarrior/blob/41992d484909bd865bc252e99e588c5c3f37c71a/taskchampion/taskchampion/src/storage/op.rs#L10-L38
This is how we accomplish `task sync` -- different replicas share the set of operations they have applied, and resolve any conflicts in a reasonable, consistent way.

Note that a single command-line invocation may produce several operations. For example
```
task 123 start +inprogress prio:M
```
would create four `Update` operations: one to set the `start` property to the current time, one to add the `tag_inprogress` property, one to set the `priority` property to `M` and one to update the `modified` property to the current time.

There are also `UndoPoint` operations, which do not actually change anything but act as a signpost for how many operations to revert when running `task undo` -- that command basically reverts operations until it reaches an `UndoPoint`.  The `UndoPoint` operations are not sent to the server.

Once operations are successfully sent to the server, they are no longer stored locally. This avoids the local task database growing forever.

Currently, none of this is visible in Taskchampion's public API. This bug would change that.

## Motivation

We'll need this for a few reasons:

The `task undo`  command _previously_ showed a "diff" of what it would change, and asked the user for permission. This is not possible with the current Taskchampion API (see https://github.com/GothenburgBitFactory/taskwarrior/commit/4b814bc602a365342a7ebb101c8d156f8cd4a15a). But if there was a way to query Taskchampion to say "hey, what are the operations back to the latest `UndoPoint`?" then it could generate a diff view from that. 

The `task info` command has historically used the undo information to show the history for a particular task. This operated by scanning the entire undo history for records matching that task's uuid, and formatting those nicely for display. Again, that's currently impossible (support was removed in GothenburgBitFactory/taskwarrior#3060). If there was a way to query Taskchampion to say "hey, what operations have happened for this task?" then we could bring back that functionality.

Looking forward, one of the things we've considered in GothenburgBitFactory/taskchampion#372 is to allow a user of the Taskchampion API to provide a list of operations to apply, instead of calling methods like `task.start(..)` or `task.set_description(..)`.  A different possibility we've considered is that a user of the Taskchampion API could call methods like `task.start(..)` or `task.set_description(..)` and build up a list of operations, then "commit" those all at once. This would allow the `task` command to confirm changes with the user before committing them, for example. All of this paragraph is out of scope for this issue, but should be kept in mind when designing the API.

## Details

Off the top of my head, I think this can be broken into two parts:

### Operations for Undo

 * Making the ReplicaOp type public
 * Defining an API on the Replica type for fetching all operations back to the latest UndoPoint, and implementing that through the storage layer.
 * Adding a C interface in `taskchampion-lib`
 * Adding a C++ interface
 * Writing some C++ support for printing a list of operations as a "diff"
 * Using this for confirmation of `task undo`

### Operations for Info

all of the above, and..

 * Updating the Taskchampion storage backend to store operations for each task for as long as that task exists. This is different from just storing all operations in the order they occurred, because once a task is deleted we want to also delete its associated operations. This will require changing the database schema.
 * Making that information available from the Replica type
 * Adding a C interface in `taskchampion-lib`
 * Adding a C+ interface
 * Using this to show a task's history in `task info` when the `journal.info` config is enabled.

### PR DESCRIPTION
**Pull request by djmitche**
This stores all operations for all existing tasks, including operations that were entered on other replicas, and makes those available via `get_task_operations`. This functionality will support `task info` in TaskWarrior, and can support similar "task history" displays in other consumers.

As the last commit and the docstrings describe, this isn't perfect -- if there are conflicting operations, then the results may differ between replicas. But those are rare, and in practice this is sufficient to provide information to users. In particular, users who never `task sync` will see correct information.

This is a large diff, but broken up into commits, many of which were reviewed and landed previously, but backed out for the 0.8.0 release.  Feel free to review commit-by-commit.

Fixes #373.

### CODE REVIEW

File: taskchampion/src/operation.rs [hunk 1]
```diff
@@ -55,6 +56,85 @@ impl Operation {
...
+                        },
+                    ) => Equal
+                        // Sort Updates principally by timestamp.
+                        .then(uuid1.cmp(uuid2))
+                        .then(timestamp1.cmp(timestamp2))
+                        .then(property1.cmp(property2))
+                        .then(value1.cmp(value2))
+                        .then(old_value1.cmp(old_value2)),
+                    (UndoPoint, UndoPoint) => Equal,
+                    // a and b are always the same variant.
```
Comment (ryneeverett) [inline taskchampion/src/operation.rs]: "a and b"? Does this comment refer to the default/unreachable case? I don't understand it.

File: taskchampion/src/operation.rs [hunk 2]
```diff
@@ -55,6 +56,85 @@ impl Operation {
...
+    /// multiple creations of the same task.
+    fn cmp(&self, other: &Self) -> Ordering {
+        use Operation::*;
+        use Ordering::*;
+        fn type_idx(op: &Operation) -> u8 {
+            match op {
+                Create { .. } => 1,
+                Update { .. } => 2,
+                Delete { .. } => 3,
+                UndoPoint => 4,
```
Comment (ryneeverett) [inline taskchampion/src/operation.rs]: I understand that UndoPoint's come first because they have no uuid but it seems a little too clever and potentially confusing to make them "4". Maybe `u8::MAX` to make it more clearly a throwaway value? An explanatory comment wouldn't hurt.

File: taskchampion/src/taskdb/sync.rs [hunk 3]
```diff
@@ -129,6 +139,12 @@ pub(super) fn sync(
         }
     }
 
+    // Add the transformed server ops to the DB. Critically, these are immediately marked as synced
+    // and thus not subject to any of the invariants around operations and task state.
+    for o in transformed_server_ops {
+        txn.add_operation(dbg!(o).into_op())?;
```
Comment (ryneeverett) [inline taskchampion/src/taskdb/sync.rs]: dbg!

File: taskchampion/src/taskdb/sync.rs [hunk 4]
```diff
@@ -129,6 +139,12 @@ pub(super) fn sync(
         }
     }
 
+    // Add the transformed server ops to the DB. Critically, these are immediately marked as synced
```
Comment (ryneeverett) [inline taskchampion/src/taskdb/sync.rs:142]: "Critically, these are immediately marked as synced" -- Where does this marking happen? (Underlying question: How are we confident that this critical assertion is true?) In the inmemory implementation it appears to be the opposite (`operations.push((false, op));`).

File: taskchampion/src/taskdb/sync.rs [hunk 5]
```diff
@@ -278,6 +305,50 @@ mod test {
         sync(&mut server, db1.storage.txn()?.as_mut(), false).unwrap();
         assert_eq!(db1.sorted_tasks(), db2.sorted_tasks());
 
+        for (dbnum, db) in [(1, &mut db1), (2, &mut db2)] {
+            dbg!(dbnum);
```
Comment (ryneeverett) [inline taskchampion/src/taskdb/sync.rs]: dbg! (I presume one would never intentionally commit a dbg! even in a test?)

File: taskchampion/src/replica.rs [hunk 6]
```diff
@@ -796,6 +823,37 @@ mod tests {
...
+        let uuid3 = Uuid::new_v4();
+
+        let mut rep = Replica::new_inmemory();
+
+        let mut ops = Operations::new();
+        ops.push(Operation::UndoPoint);
+        rep.create_task(uuid1, &mut ops).unwrap();
+        ops.push(Operation::UndoPoint);
+        rep.create_task(uuid2, &mut ops).unwrap();
+        rep.commit_operations(dbg!(ops))?;
```
Comment (ryneeverett) [inline taskchampion/src/replica.rs]: dbg!

File: taskchampion/src/storage/sqlite.rs [hunk 7]
```diff
@@ -107,17 +107,11 @@ impl SqliteStorage {
         for q in create_tables {
             con.execute(q, []).context("Creating table")?;
         }
-        // At this point the DB schema is that of TaskChampion 0.7.0.
+
+        // -- At this point the DB schema is that of TaskChampion 0.7.0.
```
Comment (ryneeverett) [inline taskchampion/src/storage/sqlite.rs]: Should all the "0.7.0" version references (also appearing as "0_7_0") be bumped to "0.8.0"?

**Review by ryneeverett — APPROVED** [review]

File: taskchampion/src/taskdb/sync.rs (hunk 4 above)
Comment (djmitche) [reply taskchampion/src/taskdb/sync.rs:142]: The `sync_complete` call just below does so. I'll clairfy.

Comment (ryneeverett) [reply taskchampion/src/taskdb/sync.rs:142]: Oh, that makes perfect sense. As I figured, there is a simple answer and I just wasn't making the connection.

**Comment by djmitche** [comment]
I added commits for some of the comments, and updated existing commits for the minor bits (dbg!, mostly)

**Review by ryneeverett — APPROVED** [review]
