### PR TITLE
Fix credential path

### LINKED ISSUE #380: Fix redundant guards
`cargo clippy` will show a few errors about redundant guards in `taskchampion/src/server/sync/mod.rs`. Fix those up!

### PR DESCRIPTION
**Pull request by QuantumBJump**
A few things fixed here:
* `credential_path.unwrap() == ""` doesn't work - `unwrap()` forcibly crashes the program if the `Option` is `None`, therefore it can't be compared to a string. `is_none()` is what we want here.
* the `credential_path.is_none()` was impossible to evaluate as true anyway, because if the credential path wasn't set, the `unwrap()` on line 32 would have crashed the program before line 33 got to resolve.
* moving the setting of `credentialpathstring` after the `is_none()` check (which doesn't take ownership of the variable) both fixes that and removes the need for the `clone()`.

This should mean that if the default credential path isn't set, `ClientConfig::default().with_auth()` which was unreachable before, should successfully run.

### CODE REVIEW

File: taskchampion/src/server/cloud/gcp.rs [hunk 1]
```diff
@@ -181,7 +180,7 @@ impl<'a> ObjectIterator<'a> {
     fn fetch_batch(&mut self) -> Result<()> {
         let mut page_token = None;
         if let Some(ref resp) = self.last_response {
-            page_token = resp.next_page_token.clone();
+            page_token.clone_from(&resp.next_page_token.clone());
```
Comment (djmitche) [inline taskchampion/src/server/cloud/gcp.rs]:
```suggestion
            page_token.clone_from(&resp.next_page_token);
```

File: taskchampion/src/server/cloud/gcp.rs [hunk 2]
```diff
@@ -29,12 +29,11 @@ impl GcpService {
...
-        let credentialpathstring = credential_path.clone().unwrap();
-        let config: ClientConfig = if credential_path.unwrap() == "" {
-            rt.block_on(ClientConfig::default().with_auth())?
-        } else {
-            let credentials = rt.block_on(CredentialsFile::new_from_file(credentialpathstring))?;
+        let config: ClientConfig = if let Some(credentials) = credential_path {
+            let credentials = rt.block_on(CredentialsFile::new_from_file(credentials))?;
             rt.block_on(ClientConfig::default().with_credentials(credentials))?
+        } else {
+            rt.block_on(ClientConfig::default().with_auth())?
```
Comment (djmitche) [inline taskchampion/src/server/cloud/gcp.rs:36]: Yikes, that was on me for not reviewing carefully. Thanks for fixing it up!

**Review by djmitche — CHANGES_REQUESTED** [review]
One little fix, if you agree. Thank you!

**Review by djmitche — APPROVED** [review]
